#include "xyz.h"
#include <fstream>
#include <sstream>
#include <iostream>

std::pair<std::vector<std::string>, Eigen::MatrixXd> read_xyz(const std::string &filename) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("Could not open file " + filename);
    }

    std::string line;
    std::getline(file, line);
    int atom_count = std::stoi(line);

    std::getline(file, line); // Comment line

    std::vector<std::string> names(atom_count);
    Eigen::MatrixXd positions(3, atom_count);

    for (int i = 0; i < atom_count; ++i) {
        std::getline(file, line);
        std::istringstream iss(line);
        iss >> names[i] >> positions(0, i) >> positions(1, i) >> positions(2, i);
    }

    file.close();
    return {names, positions};
}

void write_xyz(const std::string &filename, const Atoms &atoms) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        throw std::runtime_error("Could not open file " + filename);
    }

    int atom_count = atoms.positions.cols();
    file << atom_count << "\n";
    file << "Generated by MolecularDynamics simulation\n";

    for (int i = 0; i < atom_count; ++i) {
        file << "H " << atoms.positions(0, i) << " " << atoms.positions(1, i) << " " << atoms.positions(2, i) << "\n";
    }

    file.close();
}
